name: Sync berkeley-function-call-leaderboard Folder to AIOpsPlus Repo BFCL-CN

on:
  push:
    branches: [main]     # 监听 main 分支的推送
    paths:               # 仅当 berkeley-function-call-leaderboard/** 路径下有变更时触发
      - 'berkeley-function-call-leaderboard/**'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout HolgerZhang/gorilla
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install git-filter-repo
        run: |
          pip install git-filter-repo

      - name: Setup SSH keys
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Configure known hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Extract berkeley-function-call-leaderboard folder history
        run: |
          git filter-repo --path berkeley-function-call-leaderboard/ --to-subdirectory / --force

      - name: Push to AIOpsPlus Repo BFCL-CN
        run: |
          git config --global user.email "HolgerZhang@outlook.com"
          git config --global user.name "Holger Zhang (Sync Bot)"
          git remote add aiopsplus-repo git@github.com:aiopsplus/BFCL-CN.git
          git push aiopsplus-repo main --force